import { Category } from "@/types/menu"

// Demo menu items
export const demoCategories: Category[] = [
  {
    id: "cat-1",
    name: "Starters",
    description: "Begin your meal with these delicious appetizers",
    items: [
      {
        id: "item-1",
        name: "Crispy Calamari",
        description: "Lightly breaded calamari rings served with marinara sauce and lemon aioli",
        price: 14.99,
        image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&auto=format&fit=crop",
        tags: ["popular"],
        dietaryTags: [],
        isAvailable: true,
      },
      {
        id: "item-2",
        name: "Bruschetta",
        description: "Grilled bread rubbed with garlic and topped with fresh tomatoes, basil, and olive oil",
        price: 9.99,
        image: "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=800&auto=format&fit=crop",
        tags: [],
        dietaryTags: ["vegetarian", "vegan"],
        isAvailable: true,
      },
      {
        id: "item-3",
        name: "Buffalo Wings",
        description: "Crispy chicken wings tossed in spicy buffalo sauce, served with ranch",
        price: 12.99,
        image: "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=800&auto=format&fit=crop",
        tags: ["spicy"],
        dietaryTags: [],
        spiceLevel: 3,
        isAvailable: true,
      },
      {
        id: "item-4",
        name: "Spinach Artichoke Dip",
        description: "Creamy blend of spinach, artichoke hearts, and melted cheese with tortilla chips",
        price: 11.99,
        image: "https://images.unsplash.com/photo-1576506295286-5cda18df43e7?w=800&auto=format&fit=crop",
        tags: [],
        dietaryTags: ["vegetarian"],
        isAvailable: true,
      },
    ],
  },
  {
    id: "cat-2",
    name: "Main Courses",
    description: "Hearty dishes to satisfy your appetite",
    items: [
      {
        id: "item-5",
        name: "Grilled Salmon",
        description: "Fresh Atlantic salmon with lemon herb butter, served with seasonal vegetables and rice",
        price: 28.99,
        image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&auto=format&fit=crop",
        tags: ["popular"],
        dietaryTags: ["gluten-free"],
        calories: 650,
        isAvailable: true,
      },
      {
        id: "item-6",
        name: "Ribeye Steak",
        description: "12oz USDA Prime ribeye, grilled to perfection with garlic butter and crispy fries",
        price: 42.99,
        image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&auto=format&fit=crop",
        tags: ["popular"],
        dietaryTags: ["gluten-free"],
        calories: 980,
        isAvailable: true,
      },
      {
        id: "item-7",
        name: "Chicken Parmesan",
        description: "Breaded chicken breast topped with marinara and melted mozzarella, served with spaghetti",
        price: 22.99,
        image: "https://images.unsplash.com/photo-1632778149955-e80f8ceca2e8?w=800&auto=format&fit=crop",
        tags: [],
        dietaryTags: [],
        isAvailable: true,
      },
      {
        id: "item-8",
        name: "Vegetable Stir Fry",
        description: "Fresh seasonal vegetables wok-tossed in ginger soy sauce with jasmine rice",
        price: 16.99,
        image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&auto=format&fit=crop",
        tags: [],
        dietaryTags: ["vegetarian", "vegan"],
        calories: 420,
        isAvailable: true,
      },
      {
        id: "item-9",
        name: "Lobster Tail",
        description: "Butter-poached Maine lobster tail with drawn butter and asparagus",
        price: 54.99,
        image: "https://images.unsplash.com/photo-1559737558-2f5a35f4523b?w=800&auto=format&fit=crop",
        tags: ["new"],
        dietaryTags: ["gluten-free"],
        isAvailable: true,
      },
    ],
  },
  {
    id: "cat-3",
    name: "Pasta",
    description: "Handmade pasta dishes from our kitchen",
    items: [
      {
        id: "item-10",
        name: "Fettuccine Alfredo",
        description: "Fresh fettuccine in a rich and creamy parmesan sauce",
        price: 18.99,
        image: "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=800&auto=format&fit=crop",
        tags: [],
        dietaryTags: ["vegetarian"],
        isAvailable: true,
      },
      {
        id: "item-11",
        name: "Spaghetti Bolognese",
        description: "Classic meat sauce slow-simmered with tomatoes, herbs, and red wine",
        price: 19.99,
        image: "https://images.unsplash.com/photo-1622973536968-3ead9e780960?w=800&auto=format&fit=crop",
        tags: ["popular"],
        dietaryTags: [],
        isAvailable: true,
      },
      {
        id: "item-12",
        name: "Penne Arrabbiata",
        description: "Penne pasta in a spicy tomato sauce with garlic and red pepper flakes",
        price: 16.99,
        image: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800&auto=format&fit=crop",
        tags: ["spicy"],
        dietaryTags: ["vegetarian", "vegan"],
        spiceLevel: 2,
        isAvailable: true,
      },
    ],
  },
  {
    id: "cat-4",
    name: "Desserts",
    description: "Sweet endings to your meal",
    items: [
      {
        id: "item-13",
        name: "Tiramisu",
        description: "Classic Italian dessert with espresso-soaked ladyfingers and mascarpone cream",
        price: 9.99,
        image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800&auto=format&fit=crop",
        tags: ["popular"],
        dietaryTags: ["vegetarian"],
        isAvailable: true,
      },
      {
        id: "item-14",
        name: "Chocolate Lava Cake",
        description: "Warm chocolate cake with a molten center, served with vanilla ice cream",
        price: 10.99,
        image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&auto=format&fit=crop",
        tags: [],
        dietaryTags: ["vegetarian"],
        isAvailable: true,
      },
      {
        id: "item-15",
        name: "New York Cheesecake",
        description: "Creamy cheesecake with graham cracker crust and berry compote",
        price: 8.99,
        image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=800&auto=format&fit=crop",
        tags: [],
        dietaryTags: ["vegetarian"],
        isAvailable: true,
      },
    ],
  },
  {
    id: "cat-5",
    name: "Beverages",
    description: "Refreshing drinks to complement your meal",
    items: [
      {
        id: "item-16",
        name: "Fresh Lemonade",
        description: "House-made lemonade with fresh squeezed lemons and mint",
        price: 4.99,
        image: "https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=800&auto=format&fit=crop",
        tags: [],
        dietaryTags: ["vegan"],
        isAvailable: true,
      },
      {
        id: "item-17",
        name: "Iced Coffee",
        description: "Cold brew coffee served over ice with your choice of milk",
        price: 5.99,
        image: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=800&auto=format&fit=crop",
        tags: [],
        dietaryTags: ["vegetarian"],
        isAvailable: true,
      },
      {
        id: "item-18",
        name: "Tropical Smoothie",
        description: "Mango, pineapple, and coconut blended with yogurt",
        price: 6.99,
        image: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=800&auto=format&fit=crop",
        tags: [],
        dietaryTags: ["vegetarian"],
        isAvailable: true,
      },
    ],
  },
]

export const demoRestaurant = {
  id: "demo",
  slug: "demo-bistro",
  name: "Demo Bistro",
  description: "A modern American restaurant with global influences",
  logo: null,
  coverImage: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&auto=format&fit=crop",
  primaryColor: "#2563eb",
  secondaryColor: "#1e40af",
  fontFamily: "inter",
  categories: demoCategories,
}
